[Interface]
Address = 10.7.0.8/24, fddd:2c4:2c4:2c4::8/64
DNS = 1.1.1.1, 1.0.0.1
PrivateKey = aA7neybMIoB8qHjTcm57W+ntibsmh/eh51aID6eLeHA=

[Peer]
PublicKey = hUfKUTWTUHnDsdUwiom9Ik62+OnPF/4yKjbWuBcP6Tc=
PresharedKey = 9XtElQMpNx/dIvPKC8LsdmUuQ6qNr3xsyzsezlU7cH8=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 98.88.237.114:51820
PersistentKeepalive = 25
